"""Initial migration

Revision ID: 6d952cbe6c1b
Revises: 
Create Date: 2025-07-02 22:28:08.996288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d952cbe6c1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_overviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.String(length=500), nullable=False))
        batch_op.drop_column('search_query')

    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.String(length=500), nullable=False))
        batch_op.drop_column('search_query')

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_query', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('query')

    with op.batch_alter_table('ai_overviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_query', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('query')

    # ### end Alembic commands ###
